# This script will, when given a bed formatted file with single base mutation entries and a corresponding fasta genome file,
# create a bed file with an expanded tri/pentanucleotide context around the mutation.
# The input files will be selected using a tkinter interface for ease of use.

from TkinterDialog import TkinterDialog, Selections
from UsefulBioinformaticsFunctions import bedToFasta, FastaFileIterator
import os

# Expands the range of each mutation position in the original mutation file to encompass one extra base on either side.
def expandBedPositions(inputBaseBedFilePath,bedExpansionFilePath,contextNum):
    "Expands the range of each mutation position in the original mutation file to encompass one extra base on either side."

    with open(bedExpansionFilePath,'w') as bedExpansionFile:
        with open(inputBaseBedFilePath, 'r') as inputBaseBedFile:

            print("Writing expanded mutation indicies to intermediate bed file...")
            for line in inputBaseBedFile:

                # Get a list of all the arguments for a single mutation in the bed file.
                choppedUpLine = line.strip().split('\t')

                # Make sure the line is in a single-nucleotide context.
                if not int(choppedUpLine[1]) - int(choppedUpLine[2]) == -1:
                    raise ValueError(line + " does not give a single nucleotide location to expand.")

                # Expand the position of the mutation to be one extra base on either side.
                choppedUpLine[1] = str(int(choppedUpLine[1]) - int(contextNum/2))
                choppedUpLine[2] = str(int(choppedUpLine[2]) + int(contextNum/2))

                # Write the results to the intermediate expansion file as long as it is not at the start of the chromosome.
                if int(choppedUpLine[1]) > -1: bedExpansionFile.write("\t".join(choppedUpLine)+"\n")
                else: print("Mutation at chromosome", choppedUpLine[0], "with expanded start pos", choppedUpLine[1],
                            "extends into invalid positions.  Skipping.")


# Uses the expanded reads fasta file to create a new bed file with the expanded mutational context.
def generateExpandedContext(inputBaseBedFilePath,fastaReadsFilePath,expandedContextFilePath,contextNum):
    "Uses the expanded reads fasta file to create a new bed file with the expanded mutational context."

    print("Using fasta file to write expanded context to new bed file...")
    # Open the singlenuc context bed file and the expanded fasta reads that will be combined to create the expanded context.
    with open(inputBaseBedFilePath, 'r') as inputBaseBedFile:
        with open(fastaReadsFilePath, 'r') as fastaReadsFile:
            with open(expandedContextFilePath, 'w') as expandedContextFile:

                # Work through the singlenuc context bed file one mutation at a time.
                for fastaEntry in FastaFileIterator(fastaReadsFile):

                    # Find the singlenuc entry corresponding to this entry.
                    while True:

                        # Read in the next line
                        nextLine = inputBaseBedFile.readline()

                        # If we reached the end of the file without finding a match, we have a problem...
                        if len(nextLine) == 0:
                            raise ValueError("Reached end of single base bed file without finding a match for:",fastaEntry.sequenceLocation)

                        # Split the next line on tab characters and check for a match with the current read in the fasta file.
                        choppedUpLine = nextLine.strip().split("\t")
                        if (str(int(fastaEntry.startPos)+int(contextNum/2)) == choppedUpLine[1] and fastaEntry.chromosome == choppedUpLine[0] and 
                            fastaEntry.strand == choppedUpLine[5]): break

                    # Replace the mutation's singlenuc context with the expanded context.
                    choppedUpLine[3] = fastaEntry.sequence

                    # Write the result to the new expanded context file.
                    expandedContextFile.write("\t".join(choppedUpLine)+"\n")


def expandContext(inputBaseBedFilePaths, humanGenomeFastaFilePath, expansionContextNum):
    
    expandedContextFilePaths = list() # A list of paths to the output files generated by the function

    # Set the name of the type of context being used.
    if expansionContextNum == 3: contextText = "trinuc"
    elif expansionContextNum == 5: contextText = "pentanuc"

    for inputBaseBedFilePath in inputBaseBedFilePaths:

        print("\nWorking in:",os.path.split(inputBaseBedFilePath)[1])
        if not "_singlenuc_context" in os.path.split(inputBaseBedFilePath)[1]:
            raise ValueError("Error:  Expected file with \"_singlenuc_context\" in the name.")

        # Get some information on the file system and generate file paths for convenience.
        workingDirectory = os.path.dirname(inputBaseBedFilePath) # The working directory for the current data group
        dataGroupName = os.path.split(inputBaseBedFilePath)[1].split("_singlenuc_context")[0] # The name of mutation data group
        bedExpansionFilePath = os.path.join(workingDirectory,"intermediate_files",dataGroupName+"_intermediate_expansion.bed")
            # The path to an intermediate file fed to bedtools to generate the expanded sequence.
        fastaReadsFilePath = os.path.join(workingDirectory,"intermediate_files",dataGroupName+"_"+contextText+"_reads.fa")
            # The path to an intermediate fasta file that contains the expanded reads generated from the locations in the bedExpansion file.
        expandedContextFilePath = os.path.join(workingDirectory,dataGroupName+"_"+contextText+"_context_mutations.bed") # The final output file.

        # Create a directory for intermediate files if it does not already exist...
        if not os.path.exists(os.path.join(workingDirectory,"intermediate_files")):
            os.mkdir(os.path.join(workingDirectory,"intermediate_files"))

        # Expand the nucleotide coordinates in the singlenuc context bed file as requested.
        expandBedPositions(inputBaseBedFilePath,bedExpansionFilePath,expansionContextNum)

        # Convert the expanded coordinates in the bed file to the referenced nucleotides in fasta format.
        bedToFasta(bedExpansionFilePath,humanGenomeFastaFilePath,fastaReadsFilePath)

        # Using the newly generated fasta file, create a new bed file with the expanded context.
        generateExpandedContext(inputBaseBedFilePath,fastaReadsFilePath,expandedContextFilePath,expansionContextNum)

        expandedContextFilePaths.append(expandedContextFilePath)

        # Delete the input file, which has the same mutation information, but a smaller context.
        print("Deleting old mutation context file...")
        if inputBaseBedFilePath == expandedContextFilePath:
            raise ValueError("Input and output files have same path.  Not deleting.")
        os.remove(inputBaseBedFilePath)

    return expandedContextFilePaths


if __name__ == "__main__":

    # Create the Tkinter dialog.
    dialog = TkinterDialog(workingDirectory=os.path.join(os.path.dirname(__file__),"..","data"))
    dialog.createLabel("Note: Either single-base or trinuc context bed files will suffice.  Both are not necessary.",0,0,4)
    dialog.createMultipleFileSelector("Single-Base Bed File:",1,"singlenuc_context_mutations.bed",("Bed Files",".bed"))
    dialog.createMultipleFileSelector("Trinuc Context Bed File:",2,"trinuc_context_mutations.bed",("Bed Files",".bed"))
    dialog.createFileSelector("Human Genome Fasta File:",3,("Fasta Files",".fa"))
    dialog.createDropdown("Expansion Context",4,0,("Trinuc", "Pentanuc"))
    dialog.createReturnButton(5,0,2)
    dialog.createQuitButton(5,2,2)

    # Run the UI
    dialog.mainloop()

    # If no input was received (i.e. the UI was terminated prematurely), then quit!
    if dialog.selections is None: quit()

    # Get the user's input from the dialog.
    selections: Selections = dialog.selections
    inputBaseBedFilePaths = list(selections.getFilePathGroups())[0] # A list of paths to original bed mutation files
    trinucContextBedFilePaths = list(selections.getFilePathGroups())[1] # A list of paths to trinuc context bed mutation files
    humanGenomeFastaFilePath = list(selections.getIndividualFilePaths())[0] # The path to the human genome fasta file
    expansionContext = list(selections.getDropdownSelections())[0] # What context the file should be expanded to.

    if expansionContext == "Trinuc":
        expansionContextNum = 3
    elif expansionContext == "Pentanuc":
        expansionContextNum = 5
    else: raise ValueError("Matching strings is hard.")

    expandContext(inputBaseBedFilePaths + trinucContextBedFilePaths, humanGenomeFastaFilePath, expansionContextNum)